site_name: The Cloudy Wiki

repo_url: https://github.com/cloudy-org
repo_name: cloudy-org
edit_uri: wiki/edit/main/docs/

plugins:
  - search
  - section-index

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.snippets:
      base_path: ["snippets"]
      check_paths: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  custom_dir: overrides
  logo: assets/clouds.png
  favicon: assets/clouds.png
  icon:
    repo: octicons/git-merge-16
  font:
    text: Roboto
  palette:
    scheme: slate
    primary: red
    accent: red
  features:
    - content.action.edit
    - search.suggest
    - toc.follow
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - content.footnote.tooltips

site_author: cloudy-org
copyright: Copyright &copy; 2025 - 2026 Goldy

extra:
  generator: false
  social:
    - icon: octicons/git-merge-16
      link: https://github.com/cloudy-org

extra_css:
  - css/extra.css

watch:
  - docs
  - overrides